# Evaluación 2

## Nelson Posada Nava

In [6]:
import numpy as np

# Parte 1: Creación y manipulación de arrays

### **Crear un array:** Crea un array de 10 elementos enteros aleatorios entre 1 y 100. Imprime el array generado.

In [10]:
array_random = np.random.randint(1, 101, size=10)
print(array_aleatorio)

[60 17 40  8 91 11 25 59 91 35]


### **Reshape:** A partir del array anterior, convierte este array en una matriz de 2x5.

In [11]:
mat_2x5 = array_random.reshape(2, 5)
print(mat_2x5)

[[98 60 65 72 68]
 [33 67 96 77 88]]


### **Indexación y slicing:** De la matriz obtenida, extrae la primera fila y la última columna. Imprime ambos resultados por separado.


In [18]:
primera_fila = mat_2x5[0, :]

ultima_columna = mat_2x5[:, -1]

print("primera fila: " , primera_fila)
print("última columna: ", ultima_columna)


primera fila:  [98 60 65 72 68]
última columna:  [68 88]


### **Modificación:** Cambia el valor de los elementos en la segunda fila a ceros.

In [22]:
mat_2x5[1, :] = 0
print(mat_2x5)


[[98 60 65 72 68]
 [ 0  0  0  0  0]]


# Parte 2: Operaciones básicas con NumPy

## **Operaciones aritméticas:**

### Crea dos arrays de 5 elementos enteros aleatorios entre 1 y 50.

In [24]:
array1 = np.random.randint(1, 51, size=5)
array2 = np.random.randint(1, 51, size=5)

print("Array 1: ", array1)
print("Array 2: ", array2)


Array 1:  [ 4 36  6 29 10]
Array 2:  [15 36 37 39 50]


### Suma ambos arrays y luego multiplícalos entre sí.

In [25]:
suma = array1 + array2

mult = array1 * array2

print("suma: " , suma)

print("multiplicación: ", mult)

suma:  [19 72 43 68 60]
multiplicación:  [  60 1296  222 1131  500]


### Calcula el promedio y la desviación estándar de los resultados obtenidos.

In [26]:
promedio_suma = np.mean(suma)
desviacion_suma = np.std(suma)

promedio_mult = np.mean(mult)
desviacion_mult = np.std(mult)

print("Promedio de la suma:", promedio_suma)
print("Desviación estándar de la suma:", desviacion_suma)
print("Promedio del producto:", promedio_mult)
print("Desviación estándar del producto:", desviacion_mult)


Promedio de la suma: 52.4
Desviación estándar de la suma: 19.4381069037085
Promedio del producto: 641.8
Desviación estándar del producto: 490.3314797155084


### Condiciones lógicas: Genera un array de 20 números aleatorios entre 0 y 1. Usa condiciones lógicas para reemplazar los valores menores a 0.5 con 0 y los valores mayores o iguales a 0.5 con 1.



In [31]:
array_random = np.random.rand(20)

array_modificado = np.where(array_random < 0.5, 0, 1)

print("Array original:", array_random)
print("Array modificado:", array_modificado)


Array original: [0.13403191 0.08097599 0.61083339 0.10872546 0.87790541 0.7308375
 0.53734631 0.07660427 0.4578083  0.72619357 0.36082046 0.70211939
 0.20976125 0.9916341  0.30101894 0.2343803  0.41408282 0.35205919
 0.092647   0.11996459]
Array modificado: [0 0 1 0 1 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0]


### **Producto escalar:** Crea dos arrays de tamaño 3x3. Calcula el producto escalar entre ambos.

In [35]:
array_1 = np.random.randint(1, 11, size=(3, 3))
array_2 = np.random.randint(1, 11, size=(3, 3))

producto_escalar = np.dot(array_1, array_2)

print("Array 1:\n", array_1)
print("Array 2:\n", array_2)
print("Producto escalar:\n", producto_escalar)

Array 1:
 [[ 5 10  6]
 [ 5  3  9]
 [ 9  9  7]]
Array 2:
 [[9 8 9]
 [8 4 3]
 [8 9 3]]
Producto escalar:
 [[173 134  93]
 [141 133  81]
 [209 171 129]]


# Parte 3: Análisis de datos con NumPy

## **Operaciones aritméticas:**

### **Matriz de datos:** Crea una matriz de 5 filas y 4 columnas que contenga datos aleatorios entre 1 y 20.

In [36]:
datos = np.random.randint(1, 21, size=(5, 4))

# Imprimir la matriz
print(datos)


[[ 8  2  8 17]
 [18  5 18  8]
 [ 7  5 14  9]
 [11 12 13 13]
 [ 6  5 19 18]]


### Calcula la media de cada columna (medición).

In [38]:
media_columnas = np.mean(datos, axis=0)

print("Media de cada columna:", media_columnas)


Media de cada columna: [10.   5.8 14.4 13. ]


### Encuentra el valor máximo y mínimo de cada fila.

In [39]:
maximos_filas = np.max(datos, axis=1)
minimos_filas = np.min(datos, axis=1)

print("Máximos de cada fila:", maximos_filas)
print("Mínimos de cada fila:", minimos_filas)


Máximos de cada fila: [17 18 14 13 19]
Mínimos de cada fila: [ 2  5  5 11  5]


### Ordena las filas según los valores de la segunda columna (peso).

In [41]:
mat_ordenada = datos[np.argsort(datos[:, 1])]

print("Matriz ordenada según el peso:\n", mat_ordenada)


Matriz ordenada según el peso:
 [[ 8  2  8 17]
 [18  5 18  8]
 [ 7  5 14  9]
 [ 6  5 19 18]
 [11 12 13 13]]
